services:

  nats-cli:
    restart: "unless-stopped"
    image: natsio/nats-box:0.14.3
    command: sleep infinity

  nats-0:
    restart: "unless-stopped"
    # image: nats:2.9.25-alpine
    image: nats:2.10.17-alpine
    command: -D -c /data/nats-0.conf -cluster nats://0.0.0.0:6222 -routes nats://nats-0:6222 -routes nats://nats-1:6222 -routes nats://nats-2:6222
    ports:
      - 4320:4222
    volumes: 
      - ./config:/data
      - nats-0-js:/tmp/jetstream
      
  nats-health-0:
    restart: "unless-stopped"
    image: natsio/nats-box:0.14.3
    stop_signal: SIGKILL
    command: sleep infinity
    healthcheck:
      test: curl -sSf nats-0:8222/healthz
      interval: 0.5s
      timeout: 5s
      retries: 30
      start_period: 0s
    depends_on:
      - nats-0

  nats-1:
    restart: "unless-stopped"
    # image: nats:2.9.25-alpine
    image: nats:2.10.17-alpine
    command: -D -c /data/nats-1.conf -cluster nats://0.0.0.0:6222 -routes nats://nats-0:6222 -routes nats://nats-1:6222 -routes nats://nats-2:6222
    ports:
      - 4321:4222
    volumes: 
      - ./config:/data
      - nats-1-js:/tmp/jetstream
      
  nats-health-1:
    restart: "unless-stopped"
    image: natsio/nats-box:0.14.3
    stop_signal: SIGKILL
    command: sleep infinity
    healthcheck:
      test: curl -sSf nats-1:8222/healthz
      interval: 0.5s
      timeout: 5s
      retries: 30
      start_period: 0s
    depends_on:
      - nats-1

  nats-2:
    restart: "unless-stopped"
    # image: nats:2.9.25-alpine
    image: nats:2.10.17-alpine
    command: -D -c /data/nats-2.conf -cluster nats://0.0.0.0:6222 -routes nats://nats-0:6222 -routes nats://nats-1:6222 -routes nats://nats-2:6222
    ports:
      - 4322:4222
    volumes: 
      - ./config:/data
      - nats-2-js:/tmp/jetstream
      
  nats-health-2:
    restart: "unless-stopped"
    image: natsio/nats-box:0.14.3
    stop_signal: SIGKILL
    command: sleep infinity
    healthcheck:
      test: curl -sSf nats-2:8222/healthz
      interval: 0.5s
      timeout: 5s
      retries: 30
      start_period: 0s
    depends_on:
      - nats-2

volumes:
  nats-0-js:
  nats-1-js:
  nats-2-js:
